name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # This specifies that the workflow will run on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # The workflow will run on the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Set the version of Node.js you want to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Deploy the project to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # This is your GitHub token for authentication
